"""The names of the Enums correspond to URL parameter codes used by the VIVC API,
and values are human-readable display names."""

from enum import Enum


class BaseSearchValueEnum(Enum):
    @property
    def search_value(self) -> str:
        raise NotImplementedError


class StandardSearchValueEnum(BaseSearchValueEnum):
    """Base class for enums whose API search value is derived from the member name.

    The search value is the lowercase version of the member name, e.g.
    ``ColorOfBerrySkin.GREEN.search_value == "green"``.
    """

    @property
    def search_value(self) -> str:
        return self.name.lower()


class SearchValueEnum(BaseSearchValueEnum):
    """Base class for enums where the API search value differs from the member name.

    Each member is defined as a ``(search_value, display_name)`` tuple, where
    ``search_value`` is the opaque identifier sent to the VIVC API and
    ``display_name`` is the human-readable label stored as ``.value``, e.g.::

        Species.VITIS_RIPARIA.search_value  # "7"
        Species.VITIS_RIPARIA.value         # "VITIS RIPARIA MICHAUX"
    """

    _search_value: str

    def __new__(cls, search_value: str, display_name: str):
        obj = object.__new__(cls)
        obj._value_ = display_name
        obj._search_value = search_value
        return obj

    @property
    def search_value(self) -> str:
        return self._search_value


class ColorOfBerrySkin(StandardSearchValueEnum):
    GREEN = "BLANC"
    GREY = "GRIS"
    BLACK = "NOIR"
    RED = "ROUGE"
    ROSE = "ROSE"


class CountryOrRegion(StandardSearchValueEnum):
    AFG = "AFGHANISTAN"
    ALB = "ALBANIA"
    DZA = "ALGERIA"
    ARG = "ARGENTINA"
    ARM = "ARMENIA"
    ARM_AZE = "ARMENIA/AZERBAIJAN"
    ARM_GEO = "ARMENIA/GEORGIA"
    ASIA = "ASIA"
    AM = "ASIA MINOR"
    AUS = "AUSTRALIA"
    AUT = "AUSTRIA"
    AZE = "AZERBAIJAN"
    BAL = "BALKAN"
    BEL = "BELGIUM"
    BIH = "BOSNIA AND HERZEGOWINA"
    BRA = "BRAZIL"
    BGR = "BULGARIA"
    CAN = "CANADA"
    CAU = "CAUCASUS"
    CENTRAL_ASIA = "CENTRAL ASIA"
    CHL = "CHILE"
    CHN = "CHINA"
    CRI = "COSTA RICA"
    HRV = "CROATIA"
    CYP = "CYPRUS"
    CZE = "CZECH REPUBLIC"
    DAG = "DAGHESTAN"
    DAL = "DALMATIEN"
    DNK = "DENMARK"
    EGY = "EGYPT"
    EST = "ESTONIA"
    EUR = "EUROPE"
    FRA = "FRANCE"
    FRA_DEU = "FRANCE/GERMANY"
    GEO = "GEORGIA"
    DEU = "GERMANY"
    GRC = "GREECE"
    HUN = "HUNGARY"
    IND = "INDIA"
    IDN = "INDONESIA"
    IRN = "IRAN"
    IRQ = "IRAQ"
    ISR = "ISRAEL"
    ITA = "ITALY"
    JPN = "JAPAN"
    JOR = "JORDAN"
    KAZ = "KAZAKHSTAN"
    KOR = "KOREA"
    KGZ = "KYRGYZSTAN"
    LVA = "LATVIA"
    LBN = "LEBANON"
    LTU = "LITHUANIA"
    MLT = "MALTA"
    MEX = "MEXICO"
    MDA = "MOLDOVA"
    MNE = "MONTENEGRO"
    MAR = "MOROCCO"
    NLD = "NETHERLANDS"
    NZL = "NEW ZEALAND"
    NOR = "NORWAY"
    PAK = "PAKISTAN"
    PSE = "PALESTINIAN TERRITORY, OCCUPIED"
    PER = "PERU"
    POL = "POLAND"
    PRT = "PORTUGAL"
    PRT_DEU = "PORTUGAL/GERMANY"
    PRI = "PUERTO RICO"
    MKD = "REPUBLIC OF NORTHMACEDONIA"
    ROU = "ROMANIA"
    RUS = "RUSSIAN FEDERATION"
    SRB = "SERBIA"
    SVK = "SLOVAKIA"
    SVN = "SLOVENIA"
    SVN_HRV = "SLOVENIA/CROATIA"
    ZAF = "SOUTH AFRICA"
    ESP = "SPAIN"
    SUN = "SUN (FORMERLY USSR, UNION OF SOVIET SOCIALIST REPUBLICS)"
    CHE = "SWITZERLAND"
    SYR = "SYRIAN ARAB REPUBLIC"
    TWN = "TAIWAN, REPUBLIC OF CHINA"
    TJK = "TAJIKISTAN"
    TUN = "TUNISIA"
    TUR = "TURKEY"
    TKM = "TURKMENISTAN"
    UKR = "UKRAINE"
    GBR = "UNITED KINGDOM"
    USA = "UNITED STATES OF AMERICA"
    URY = "URUGUAY"
    UZB = "UZBEKISTAN"
    YEM = "YEMEN"
    YUG = "YUGOSLAVIA"


class Utilization(StandardSearchValueEnum):
    @property
    def search_value(self) -> str:
        return super().search_value.replace("_", "+")

    WINE_GRAPE = "WINE GRAPE"
    TABLE_GRAPE = "TABLE GRAPE"
    RAISIN_GRAPE = "RAISIN GRAPE"
    ROOTSTOCK = "ROOTSTOCK"


class Species(SearchValueEnum):
    NOT_SPECIFIED = ("0", "NOT SPECIFIED")
    VITIS_VINIFERA_SUBSP_VINIFERA = ("VINIFERA", "VITIS VINIFERA LINNÉ SUBSP. VINIFERA")
    INTERSPECIFIC_CROSSING = ("INTERSPECIFIC", "INTERSPECIFIC CROSSING")
    AMPELOPSIS_ACONITIFOLIA_BUNGE = ("118", "AMPELOPSIS ACONITIFOLIA BUNGE")
    AMPELOPSIS_AEGIROPHYLLA = ("121", "AMPELOPSIS AEGIROPHYLLA")
    AMPELOPSIS_BIPINNATA = ("120", "AMPELOPSIS BIPINNATA")
    AMPELOPSIS_BODINIERI = ("64", "AMPELOPSIS BODINIERI REHDER")
    AMPELOPSIS_BREVIPEDUNCULATA = ("65", "AMPELOPSIS BREVIPEDUNCULATA VAR. MAX. W")
    AMPELOPSIS_CHAFFANJONII = ("122", "AMPELOPSIS CHAFFANJONII = WATSONIANA")
    AMPELOPSIS_CITRULLOIDES = ("66", "AMPELOPSIS CITRULLOIDES LEBAS")
    AMPELOPSIS_CORDATA = ("67", "AMPELOPSIS CORDATA MICHAUX")
    AMPELOPSIS_DELAVAYANA = ("119", "AMPELOPSIS DELAVAYANA")
    AMPELOPSIS_HETEROPHYLLA = ("68", "AMPELOPSIS HETEROPHYLLA THUNBERG")
    AMPELOPSIS_MEGALOPHYLLA = ("117", "AMPELOPSIS MEGALOPHYLLA DIELS ET GILG")
    AMPELOPSIS_SERJANIIFOLIA = ("69", "AMPELOPSIS SERJANIIFOLIA REGEL")
    AMPELOPSIS_VITIFOLIA = ("70", "AMPELOPSIS VITIFOLIA BOISSIER")
    MUSCADINIA_INTERSPECIFIC_CROSSING = ("124", "MUSCADINIA INTERSPECIFIC CROSSING")
    MUSCADINIA_POPENOEI = ("104", "MUSCADINIA POPENOEI FENNELL")
    MUSCADINIA_ROTUNDIFOLIA_VAR_ROTUNDIFOLIA = (
        "5",
        "MUSCADINIA ROTUNDIFOLIA MICHAUX VAR. ROTUNDIFOLIA",
    )
    MUSCADINIA_ROTUNDIFOLIA_VAR_MUNSONIANA = (
        "28",
        "MUSCADINIA ROTUNDIFOLIA SIMPSON VAR. MUNSONIANA",
    )
    PARTHENOCISSUS_QUINQUEFOLIA = (
        "115",
        "PARTHENOCISSUS QUINQUEFOLIA (LINNÉ) PLANCHON",
    )
    PARTHENOCISSUS_TRICUSPIDATA = (
        "116",
        "PARTHENOCISSUS TRICUSPIDATA SIEBOLD ET ZUCCARINI",
    )
    VITIS_ADENOCLADA = ("114", "VITIS ADENOCLADA HANDEL MANZETTI")
    VITIS_AESTIVALIS = ("8", "VITIS AESTIVALIS MICHAUX")
    VITIS_AMURENSIS = ("6", "VITIS AMURENSIS RUPRECHT")
    VITIS_ARIZONICA = ("33", "VITIS ARIZONICA ENGELMANN")
    VITIS_ARMATA = ("46", "VITIS ARMATA DIELS ET GILG")
    VITIS_BAIHENSIS = ("128", "VITIS BAIHENSIS NIU")
    VITIS_BAILEYANA = ("72", "VITIS BAILEYANA MUNSON")
    VITIS_BALANSAEANA = ("73", "VITIS BALANSAEANA PLANCHON")
    VITIS_BASHANICA = ("126", "VITIS BASHANICA HE")
    VITIS_BELLULA = ("74", "VITIS BELLULA (REHDERS) WANG")
    VITIS_BERLANDIERI = ("11", "VITIS BERLANDIERI PLANCHON")
    VITIS_BETULIFOLIA = ("47", "VITIS BETULIFOLIA DIELS ET GILG")
    VITIS_BLANCOII = ("75", "VITIS BLANCOII MUNSON")
    VITIS_BLOODWORTHIANA = ("76", "VITIS BLOODWORTHIANA COMEAUX")
    VITIS_BOSTURGAIENSIS = ("77", "VITIS BOSTURGAIENSIS VASSILCZENKO")
    VITIS_BOURGAEANA = ("78", "VITIS BOURGAEANA PLANCHON")
    VITIS_BOURQUINA = ("19", "VITIS BOURQUINA MUNSON")
    VITIS_BOURQUINIANA = ("9", "VITIS BOURQUINIANA MUNSON")
    VITIS_BRYONIAEFOLIA = ("79", "VITIS BRYONIAEFOLIA BUNGE")
    VITIS_CALIFORNICA = ("48", "VITIS CALIFORNICA BENTHAM")
    VITIS_CANDICANS = ("17", "VITIS CANDICANS ENGELMANN")
    VITIS_CARIBAEA = ("80", "VITIS CARIBAEA DE CANDOLLE")
    VITIS_CHAMPINII = ("10", "VITIS CHAMPINII PLANCHON")
    VITIS_CHRYSOBOTRYS = ("82", "VITIS CHRYSOBOTRYS LEVEILLE ET VANIOT")
    VITIS_CHUNGANENSIS = ("83", "VITIS CHUNGANENSIS HU")
    VITIS_CHUNGII = ("84", "VITIS CHUNGII METCALF")
    VITIS_CINEREA = ("20", "VITIS CINEREA ENGELMANN")
    VITIS_COIGNETIAE = ("27", "VITIS COIGNETIAE PULLIAT")
    VITIS_CORDIFOLIA = ("15", "VITIS CORDIFOLIA MICHAUX")
    VITIS_CORIACEA = ("50", "VITIS CORIACEA SHUTTLEWORTH")
    VITIS_CUMINGIANA = ("85", "VITIS CUMINGIANA TURCZANINOW")
    VITIS_DAVIDII = ("26", "VITIS DAVIDII (ROM. DU CAIL.) FOEX")
    VITIS_DAVIDII_CYANOCARPA = (
        "131",
        "VITIS DAVIDII (ROM. DU CAIL.) FOEX CYANOCARPA GAGNEPAIN",
    )
    VITIS_DENTICULATA = ("86", "VITIS DENTICULATA RAFINESQUE")
    VITIS_DOANIANA = ("16", "VITIS DOANIANA MUNSON")
    VITIS_EMBERGERI = ("87", "VITIS EMBERGERI GALET")
    VITIS_FICIFOLIA = ("38", "VITIS FICIFOLIA BUNGE")
    VITIS_FICIFOLIOIDES = ("88", "VITIS FICIFOLIOIDES WANG")
    VITIS_FLEXUOSA = ("89", "VITIS FLEXUOSA THUNBERG")
    VITIS_GIGAS = ("90", "VITIS GIGAS FENNELL")
    VITIS_GIRDIANA = ("51", "VITIS GIRDIANA MUNSON")
    VITIS_HANCOCKII = ("91", "VITIS HANCOCKII HANCE")
    VITIS_HELLERI = ("92", "VITIS HELLERI SMALL")
    VITIS_HEXAMERA = ("93", "VITIS HEXAMERA GAGNEPAIN")
    VITIS_HISSARICA = ("94", "VITIS HISSARICA VASSILCZENKO")
    VITIS_ILLEX = ("96", "VITIS ILLEX BAILEY")
    VITIS_INTERSPECIFIC_CROSSING = ("3", "VITIS INTERSPECIFIC CROSSING")
    VITIS_JAEGERIANA = ("97", "VITIS JAEGERIANA COMEAUX")
    VITIS_KIUSIANA = ("133", "VITIS KIUSIANA MOMIYAMA")
    VITIS_LABRUSCA = ("2", "VITIS LABRUSCA LINNÉ")
    VITIS_LANATA = ("29", "VITIS LANATA ROXBURG")
    VITIS_LINCECUMII = ("12", "VITIS LINCECUMII BUCKLEY")
    VITIS_LONGII = ("4", "VITIS LONGII PRINCE")
    VITIS_MONTICOLA = ("13", "VITIS MONTICOLA BUCKLEY")
    VITIS_NESBITTIANA = ("98", "VITIS NESBITTIANA COMEAUX")
    VITIS_NOVAE_ANGLIAE = ("34", "VITIS NOVAE ANGLIAE FERNALD")
    VITIS_NOVISINENSIS = ("99", "VITIS NOVISINENSIS VASSILCENKO")
    VITIS_PEDICELLATA = ("100", "VITIS PEDICELLATA LAWSON")
    VITIS_PENINSULARIS = ("101", "VITIS PENINSULARIS JONES")
    VITIS_PENTAGONA = ("95", "VITIS PENTAGONA DIELS ET GILG")
    VITIS_PIASEZKII = ("37", "VITIS PIASEZKII MAXIMOWICZ")
    VITIS_PILOSO_NERVA = ("103", "VITIS PILOSO NERVA METCALF")
    VITIS_PSEUDORETICULATA = ("105", "VITIS PSEUDORETICULATA WANG")
    VITIS_QINLINGENSIS = ("127", "VITIS QINLINGENSIS HE")
    VITIS_RETORDI = ("106", "VITIS RETORDI ROMANET DU CAILLAUD")
    VITIS_RIPARIA = ("7", "VITIS RIPARIA MICHAUX")
    VITIS_ROMANETII = ("53", "VITIS ROMANETII ROMANET DU CAILLAUD")
    VITIS_RUBRA = ("22", "VITIS RUBRA MICHAUX")
    VITIS_RUFOTOMENTOSA = ("31", "VITIS RUFOTOMENTOSA SMALL")
    VITIS_RUPESTRIS = ("14", "VITIS RUPESTRIS SCHEELE")
    VITIS_SEGUINII = ("107", "VITIS SEGUINII LEVEILLE")
    VITIS_SHUTTLEWORTHII = ("18", "VITIS SHUTTLEWORTHII HOUSE")
    VITIS_SILVESTRII = ("108", "VITIS SILVESTRII PAMPANINI")
    VITIS_SIMPSONII = ("23", "VITIS SIMPSONII MUNSON")
    VITIS_SINOCINEREA = ("54", "VITIS SINOCINEREA WANG")
    VITIS_SLAVINII = ("35", "VITIS SLAVINII REHDER")
    VITIS_SMALLIANA = ("55", "VITIS SMALLIANA BAILEY")
    VITIS_SPINOVITIS_DAVIDII = ("109", "VITIS SPINOVITIS DAVIDII ROMANET DU CAILLAUD")
    VITIS_THUNBERGII = ("25", "VITIS THUNBERGII SIEBOLD ET ZUCCARINA")
    VITIS_TRELEASEI = ("58", "VITIS TRELEASEI MUNSON")
    VITIS_TSOII = ("110", "VITIS TSOII MERRIL")
    VITIS_VINIFERA_SUBSP_SATIVA = (
        "1",
        "VITIS VINIFERA LINNÉ SUBSP. SATIVA (DE CANDOLLE) HEGI",
    )
    VITIS_VINIFERA_SUBSP_SYLVESTRIS = (
        "21",
        "VITIS VINIFERA LINNÉ SUBSP. SYLVESTRIS GMELIN",
    )
    VITIS_VITIS_PIASEZKII_PAGNUCCII = ("125", "VITIS VITIS PIASEZKII PAGNUCCII")
    VITIS_VULPINA = ("24", "VITIS VULPINA")
    VITIS_WENCHOWENSIS = ("111", "VITIS WENCHOWENSIS LING")
    VITIS_WENXIANENSIS = ("132", "VITIS WENXIANENSIS WANG")
    VITIS_WILSONAE = ("112", "VITIS WILSONAE VEITCH")
    VITIS_YESHANENSIS = ("30", "VITIS YESHANENSIS CHEN")
    VITIS_YUNNANENSIS = ("134", "VITIS YUNNANENSIS C.L.LI")
    VITIS_INTERGENERIC_CROSSING = ("123", "VITIS INTERGENERIC CROSSING")
